import Head from 'next/head'
import Image from 'next/image'
import { useState,useEffect } from 'react';
import { useRouter } from 'next/router'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })


  export default function Home() {
    const Newi = useRouter() 
  return (
    <>
      <Head>
        <title>News-Yo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/newsicon.jpg" />
      </Head>
      <nav>
      
      </nav>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            The daily info you need...&nbsp;
            <code className={styles.code}>:D</code>
          </p>
          <div>
            
          </div>
          {/* <div>
            <a
              // href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              // target="_blank"
              // rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div> */}
        </div>

        <div className={styles.center}>
          
          <Image
            className={styles.logo}
            src="/bgnews.jpg"
            alt="Next.js Logo"
            width={1000}
            height={320}
            priority
          />
          <a onClick={() => Newi.push('/feed/id')}>View Feed</a>
          </div>
          {/* <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div> */}
        

        <div className={styles.grid} >
       
          <a onClick={() => Newi.push('/feed/busi')}
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Business <span>-&gt;</span>
              <img src="bussiness.jpg" alt="BS" style={styles}/>
            </h2>
            <p className={inter.className}>
              Find all information about business news&nbsp;
            </p>
          </a>
          

          <a onClick={() => Newi.push('/feed/enter')}
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Entertainment <span>-&gt;</span>
              <img src="entertainment.jpg" alt="ET" width={200} height={200}/>
            </h2>
            <p className={inter.className}>
              Get the best entertainment news&nbsp;
            </p>
          </a>

          <a onClick={() => Newi.push('/feed/sports')}
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Sports<span>-&gt;</span>
              <img src="sports.jpg" alt="Sp" width={200} height={200}/>
            </h2>
            <p className={inter.className}>
              The only sports news you need&nbsp;
            </p>
          </a>

          <a onClick={() => Newi.push('/feed/learn')}
        
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
             Learn More <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {/* with&nbsp;Vercel. */}
            </p>
          </a> 
        </div>
      </main>
    </>
  )
        
}


